### ISSUE TITLE
New numerical features

### ISSUE THREAD

**Issue by asdasdqwdqwfsdf** [c-f-h/pyiga#4]
Hi!

1.) are higher order derivatives (e.g. **Second, Third  derivatives** in **2D** and 3D) supported in pyiga (in furture)?
2.) is **parallel MPI**  version possible?

Warm regards!

**Comment by c-f-h** [comment]
Hello,

1) Second (physical) derivates are implemented (in all dimensions). See the adaptive.ipynb notebook where we use this feature to compute a residual error estimator. Third and higher order derivatives are only supported in parametric coordinates since the transformations to the physical domain become very complicated.

2) MPI support is certainly possible, but not implemented at the moment. I think the best path would be to use PETSc via petsc4py.

**Comment by asdasdqwdqwfsdf** [comment]
Hello,

1) can we import third and higher order (physical)  derivatives from "**igakit**" for adaptive pyiga solver ? 

Best!

**Comment by c-f-h** [comment]
Does igakit support physical transformation of higher order derivatives? I had a quick look and only saw the parametric derivatives, but I'm not familiar with the package.
